database:
  uri: mongodb://admin:password@localhost:27017
dashboards:
  - name: Dashboard 1
    projects:
      - name: Project 1
        apps:
          - name: "Example App Name"
            description: "This is an example app description"
            current:
              data:
                name: Current Version
                description: This is the current data description
              datasource: |
                kind: jenkins
                spec:
                  release: weekly
            expected:
              data:
                name: Expected Version
                description: This is the expected description
              datasource: |
                kind: jenkins
                spec:
                  release: weekly

