server:
  readonly: false
database:
  uri: mongodb://admin:password@localhost:27017
  # uri: mongodb://admin:password@mongodb:27017
dashboards:
  - name: Updatecli
    projects:
      - name: Hugo
        description: Monitor Hugo version used accross Updatecli project
        apps:
          - name: "Github Action"
            description: "Ensure Github Action uses the latest Hugo"
            current:
              data:
                name: Current
                description: Current Hugo
              updatemanifest: |
                scms:
                  default:
                    kind: git
                    spec:
                      url: https://github.com/updatecli/website.git
                      branch: master
                sources:
                  default:
                    kind: yaml
                    scmid: default
                    spec:
                      file: .github/workflows/build.yaml
                      key: jobs.build.steps[2].with.hugo-version
            expected:
              data:
                name: Expected
                description: Latest Upstream Hugo version
              updatemanifest: |
                sources:
                  default:
                    kind: githubrelease
                    spec:
                      owner: gohugoio
                      repository: hugo
                      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
                      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
                    transformers:
                      - trimprefix: v
          - name: "Netlify"
            description: "Ensure Netlify uses the latest Hugo"
            current:
              data:
                name: Current
                description: Current Hugo
              updatemanifest: |
                scms:
                  default:
                    kind: git
                    spec:
                      url: https://github.com/updatecli/website.git
                      branch: master
                sources:
                  default:
                    kind: toml
                    scmid: default
                    spec:
                      file: netlify.toml
                      key: build.environment.HUGO_VERSION
            expected:
              data:
                name: Expected
                description: Latest Upstream Hugo version
              updatemanifest: |
                sources:
                  default:
                    kind: githubrelease
                    spec:
                      owner: gohugoio
                      repository: hugo
                      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
                      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
                    transformers:
                      - trimprefix: v

      - name: Updatecli
        description: Monitor Updatecli Version
        apps:
          - name: "Command Line"
            description: "Monitor Updatecli binary version"
            current:
              data:
                name: Current
                description: Currently latest version published
              updatemanifest: |
                sources:
                  default:
                    kind: githubrelease
                    spec:
                      owner: updatecli
                      repository: updatecli
                      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
                      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
          - name: "Github Action"
            description: "Monitor Updatecli version used withing Updatecli Github Action"
            current:
              data:
                name: Current
                description: Currently latest version published
              updatemanifest: |
                scms:
                  default:
                    kind: git
                    spec:
                      url: https://github.com/updatecli/updatecli-action.git
                      branch: v2
                sources:
                  default:
                    kind: yaml
                    scmid: default
                    spec:
                      file: action.yaml
                      key: "inputs.version.default"
            expected:
              data:
                name: Expected
                description: Expected version based on latest Updatecli version published on Github Release
              updatemanifest: |
                sources:
                  default:
                    kind: githubrelease
                    spec:
                      owner: updatecli
                      repository: updatecli
                      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
                      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
          - name: "DockerHub Image"
            description: "Monitor Latest Updatecli Docker Image tag published on DockerHub"
            current:
              data:
                name: Current
                description: Currently latest version published
              updatemanifest: |
                sources:
                  default:
                    kind: dockerimage
                    spec:
                      image: updatecli/updatecli
                      versionfilter:
                        kind: semver
            expected:
              data:
                name: Expected
                description: Expected version based on latest Updatecli version published on Github Release
              updatemanifest: |
                sources:
                  default:
                    kind: githubrelease
                    spec:
                      owner: updatecli
                      repository: updatecli
                      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
                      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'

          - name: "Ghcr Image"
            description: "Monitor Latest Updatecli Docker Image tag published on ghcr.io"
            current:
              data:
                name: Current
                description: Currently latest version published
              updatemanifest: |
                sources:
                  default:
                    kind: dockerimage
                    spec:
                      image: ghcr.io/updatecli/updatecli
                      versionfilter:
                        kind: semver
            expected:
              data:
                name: Expected
                description: Expected version based on latest Updatecli version published on Github Release
              updatemanifest: |
                sources:
                  default:
                    kind: githubrelease
                    spec:
                      owner: updatecli
                      repository: updatecli
                      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
                      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      - name: Golang
        description: Monitor Golang version used accross the Updatecli project
        apps:
          - name: "Updatecli CodeBase"
            description: "Monitor Golang version used within Updatecli"
            current:
              data:
                name: Current
                description: Currently latest version published
              updatemanifest: |
                scms:
                  default:
                    kind: git
                    spec:
                      url: https://github.com/updatecli/updatecli.git
                      branch: main
                sources:
                  default:
                    name: Get Latest Go Release
                    kind: file
                    scmid: default
                    spec:
                      file: go.mod
                      line: 3
                    transformers:
                      - trimprefix: 'go '
            expected:
              data:
                name: Expected
                description: Latest Golang version published
              updatemanifest: |
                sources:
                  default:
                    name: Get Latest Go Release
                    kind: githubrelease
                    transformers:
                      - trimprefix: go
                      - findsubmatch:
                          pattern: '^(\d*).(\d*)'
                    spec:
                        owner: golang
                        repository: go
                        token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
                        username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
                        versionfilter:
                            kind: regex
                            pattern: go1\.(\d*)\.(\d*)$

