database:
  uri: mongodb://admin:password@localhost:27017
  # uri: mongodb://admin:password@mongodb:27017
dashboards:
  - name: Dashboard 1
    projects:
      - name: Project 1
        apps:
          - name: "Example App Name"
            description: "This is an example app description"
            current:
              data:
                name: Current Version
                description: This is the current data description
              updatemanifest: |
                scms:
                  default:
                    kind: git
                    spec:
                      url: https://github.com/updatecli/updatecli-action.git
                      branch: v2
                sources:
                  default:
                    kind: yaml
                    scmid: default
                    spec:
                      file: action.yaml
                      key: "inputs.version.default"
            expected:
              data:
                name: Expected Version
                description: This is the expected description
              updatemanifest: |
                sources:
                  default:
                    kind: githubrelease
                    spec:
                      owner: updatecli
                      repository: updatecli
                      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
                      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'

