## Build final updatecli docker image
#  We on purpose release artifacts created by goreleaser
#  located in the dist directory

## Goreleaser requires the "--platform" to handle multi-platform builds
# hadolint ignore=DL3029
FROM --platform=${BUILDPLATFORM} debian:stable-slim

LABEL maintainer="Olivier Vernin <me@olblak.com>"

# Dynamic labels are defined from the goreleaser configuration ".goreleaser.yaml"
LABEL org.opencontainers.image.authors="Olivier Vernin<me@olblak.com>"
LABEL org.opencontainers.image.url="https://github.com/updatecli/updatefactory/pkgs/container/updatecli"
LABEL org.opencontainers.image.documentation="https://www.updatecli.io/docs/prologue/introduction/"
LABEL org.opencontainers.image.title="Updatefactory"
LABEL org.opencontainers.image.description="A declarative update manager"
LABEL org.opencontainers.image.base.name="ghcr.io/updatecli/updatefactory"

# /tmp is used by updatecli to store git repository so it's better
# to define a volume
VOLUME /tmp

## The latest version of these "generic" package is always required
# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
        ca-certificates \
        curl \
        tar \
        unzip \
        wget &&\ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Available files only matched against the binaries generated by the builds section
# and packages generated by the nfpms section.
COPY updatefactory  /usr/local/bin/updatefactory

RUN \
  useradd -d /home/updatefactory -U -u 1000 -m updatefactory && \
  mkdir /etc/updatefactory && \
  chmod 0660 /etc/updatefactory && \
  chown root:updatefactory /etc/updatefactory

USER updatefactory

WORKDIR /home/updatefactory

RUN mkdir /home/updatefactory/.updatefactory

ENTRYPOINT [ "/usr/local/bin/updatefactory" ]

