version: '3'
services:
  mongodb:
    image: mongo:6.0.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017

  server:
    image: ghcr.io/updatecli/updatefactory:v0.0.0-amd64
    volumes:
      - "./config.yaml:/home/updatefactory/.updatefactory/config.yaml"
    ports:
      - 8080:8080
