apiVersion: v2
appVersion: 0.1.0
dependencies:
- condition: mongodb.enabled
  name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 13.6.2
description: A release monitoring platform
name: updatemonitor
type: application
version: 0.2.0
