apiVersion: v1
kind: Secret
metadata:
  name: {{ include "updatemonitor.secretName" . }}
  labels:
    {{- include "updatemonitor.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range .Values.agents.environments }}
  {{ .name }}: {{.value -}}
  {{ end }}

