apiVersion: v1
kind: Service
metadata:
  name: updatemonitor-server
  labels:
    {{- include "updatemonitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "updatemonitor.selectorLabels.server" . | nindent 4 }}
