apiVersion: v1
kind: Service
metadata:
  name: updatemonitor-front
  labels:
    {{- include "updatemonitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "updatemonitor.selectorLabels.front" . | nindent 4 }}
