version: '3'
services:
  mongodb:
    image: mongo:6.0.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017

  server:
    image: ghcr.io/updatecli/updash:latest
    command: server start
    volumes:
      - "./config.yaml:/home/updatefactory/.updatefactory/config.yaml"
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.server.rule=Host(`localhost`) && Path(`/api/`)"
      - "traefik.http.routers.server.rule=Host(`localhost`) && Path(`/api/`)"
      - "traefik.http.middlewares.server.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.server.stripprefix.forceSlash=false"
      - "traefik.http.routers.server.service=server"
      - "traefik.http.services.server.loadbalancer.server.port=8080"

  agent:
    image: ghcr.io/updatecli/updash:latest
    command: agent start
    volumes:
      - "./config.yaml:/home/updatefactory/.updatefactory/config.yaml"
    environment:
      - UPDATECLI_GITHUB_TOKEN=${UPDATECLI_GITHUB_TOKEN}
      - UPDATECLI_GITHUB_ACTOR=${UPDATECLI_GITHUB_ACTOR}

#   front:
#     image: ghcr.io/updatecli/updash-front:latest
#     expose: 
#       - 80
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.front.rule=Host(`localhost`) && Path(`/`)"
#       - "traefik.http.routers.front.service=front"
#       - "traefik.http.services.front.loadbalancer.server.port=80"


  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
