name: Go
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Run full test once a day
    - cron: '0 0 * * *'
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      # https://github.com/actions/setup-go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required
          # and must be specified without patch version:
          # we always use the latest patch version.
          version: v1.51
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
      - name: Show GoReleaser version
        run: goreleaser --version
      - name: Build
        run: make build
    # Codecov should only be updated if make test is executed
    #- name: Upload coverage to Codecov
    #  uses: codecov/codecov-action@v3
    #  if: ${{ github.event_name == 'schedule' }}
    # Manage and run your integration tests with efficiency
    # https://github.com/ovh/venom
